### ISSUE TITLE
How to enable plugin?

### ISSUE THREAD

**Issue by simon-231** [cosmocode/dokuwiki-plugin-rating#8]
I installed the plugin and also SQL Lite. Installation worked and the plugin is enabled, however I do not see a rating control on any page. How can I enable the plugin after installing it?

**Comment by gldtn** [comment]
Yes, how to use this? I see that the sqlite database was created, but I couldn't figure out how o get the ratings option to show on a page.

Help please!

**Comment by splitbrain** [comment]
I updated the plugin's page with instructions.

**Comment by gldtn** [comment]
Thank you!

**Comment by simon-231** [comment]
@splitbrain Thank you!
